FROM openjdk:17-alpine
COPY FabrickPaymentCommand/target/FabrickPaymentCommand-0.0.1-SNAPSHOT.jar FabrickPaymentCommand-0.0.1-SNAPSHOT.jar
EXPOSE 8000
CMD ["java", "-jar","FabrickPaymentCommand-0.0.1-SNAPSHOT.jar"]
