server:
  port: 9000
springdoc:
  api-docs:
    path: /v3/api-docs
spring:
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    function:
      definition: successfulPayments;declinedPayments;failedPayments
    stream:
      kafka:
        streams:
          binder:
            configuration:
              spring.json.use.type.headers: false
          bindings:
            failedPayments-in-0:
              consumer:
                materializedAs: fail-store
            successfulPayments-in-0:
              consumer:
                materializedAs: succ-store
            declinedPayments-in-0:
              consumer:
                materializedAs: decl-store

      bindings:
        successfulPayments-in-0:
          destination: successfulPayments
        declinedPayments-in-0:
          destination: declinedPayments
        failedPayments-in-0:
          destination: failedPayments
