server:
  port: 9000
  servlet:
    context-path: /query
springdoc:
  api-docs:
    path: /api-docs
spring:
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    function:
      definition: successfulPayments;declinedPayments;failedPayment
    stream:
      kafka:
        streams:
          binder:
            configuration:
              spring.json.use.type.headers: false
          bindings:
            successfulPayments-in-0:
              consumer:
                materializedAs: succ-store
            declinedPayments-in-0:
              consumer:
                materializedAs: decl-store
            failedPayments-in-0:
              consumer:
                materializedAs: fail-store
      bindings:
        successfulPayments-in-0:
          destination: successfulPayments
        declinedPayments-in-0:
          destination: declinedPayments
        failedPayments-in-0:
          destination: failedPayments
