version: "3.9"
services:
  postgres:
    image: postgres:10-alpine3.16
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fabrick_db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  fabrick-service-container:
    build:
      context: ..
      dockerfile: ./FabrickReadAPI/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  payment-processor-container:
    build:
      context: ..
      dockerfile: ./PaymentProcessor/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/fabrick_db
      - kafka_address=kafka:9092
    depends_on:
      - payment-command-container
      - kafka
      - zookeeper
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  payment-command-container:
    build:
      context: ..
      dockerfile: ./FabrickPaymentCommand/Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  payment-query-container:
    build:
      context: ..
      dockerfile: ./FabrickPaymentQuery/Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - payment-processor-container
      - kafka
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock